import { useState, useEffect } from "react";
import { Button } from "@sonantica/ui";
import {
  IconX,
  IconDeviceFloppy,
  IconTrash,
  IconRefresh,
  IconAlertTriangle,
} from "@tabler/icons-react"; // Added icons
import { PluginService } from "../../../services/PluginService"; // Import service

interface PluginConfigModalProps {
  isOpen: boolean;
  onClose: () => void;
  config: Record<string, any>;
  onSave: (config: Record<string, any>) => Promise<void>;
  pluginName: string;
  pluginId: string; // New prop
}

export function PluginConfigModal({
  isOpen,
  onClose,
  config,
  onSave,
  pluginName,
  pluginId,
}: PluginConfigModalProps) {
  const [jsonString, setJsonString] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false); // New state

  // default config logic extracted for reuse
  const getDefaultConfig = () => {
    let defaultConfig = {};
    const nameLower = pluginName.toLowerCase();
    if (nameLower.includes("demucs")) {
      defaultConfig = {
        model: "htdemucs",
        segment: 10,
        shifts: 1,
        overlap: 0.25,
        split: true,
      };
    } else if (nameLower.includes("brain")) {
      defaultConfig = {
        batch_size: 32,
        threshold: 0.75,
        index_type: "L2",
      };
    } else if (
      nameLower.includes("workshop") ||
      nameLower.includes("downloader")
    ) {
      defaultConfig = {
        output_format: "flac",
        naming_format: "{artist}/{album}/{title}",
        download_lyrics: true,
        embed_metadata: true,
        create_artist_folder: true,
        create_album_folder: true,
        quality: "best",
        threads: 4,
      };
    }
    return defaultConfig;
  };

  useEffect(() => {
    if (isOpen) {
      if (config && Object.keys(config).length > 0) {
        setJsonString(JSON.stringify(config, null, 2));
      } else {
        setJsonString(JSON.stringify(getDefaultConfig(), null, 2));
      }
      setError(null);
    }
  }, [isOpen, config, pluginName]);

  const handleSave = async () => {
    try {
      const parsed = JSON.parse(jsonString);
      setIsSaving(true);
      await onSave(parsed);
      onClose();
    } catch (e) {
      if (e instanceof SyntaxError) {
        setError("Invalid JSON format");
      } else {
        setError("Failed to save configuration");
      }
    } finally {
      setIsSaving(false);
    }
  };

  const handleReset = () => {
    if (
      confirm("Reset configuration to defaults? Unsaved changes will be lost.")
    ) {
      setJsonString(JSON.stringify(getDefaultConfig(), null, 2));
    }
  };

  const handleDeleteData = async () => {
    if (
      confirm(
        `Are you sure you want to delete ALL data generated by ${pluginName}? This action cannot be undone.`
      )
    ) {
      try {
        setIsDeleting(true);
        await PluginService.deleteData(pluginId);
        alert("Data deletion requested.");
      } catch (e) {
        console.error(e);
        alert("Failed to delete data.");
      } finally {
        setIsDeleting(false);
      }
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <div className="bg-surface-elevated border border-border rounded-xl shadow-2xl w-full max-w-lg overflow-hidden animate-in fade-in zoom-in duration-200 flex flex-col max-h-[90vh]">
        <div className="flex items-center justify-between p-4 border-b border-border bg-surface-base shrink-0">
          <h3 className="font-semibold text-lg">{pluginName} Configuration</h3>
          <button
            onClick={onClose}
            className="p-1 hover:bg-surface-highlight rounded-md transition-colors text-text-muted hover:text-text-primary"
          >
            <IconX size={20} />
          </button>
        </div>

        <div className="p-6 space-y-6 overflow-y-auto">
          {/* Instructions */}
          <div className="text-sm text-text-muted space-y-2 bg-surface-base p-3 rounded-lg border border-border/50">
            <p className="font-medium text-text-primary">How to configure:</p>
            <ul className="list-disc list-inside space-y-1 ml-1">
              <li>Use standard JSON format.</li>
              <li>
                Workshop: Use <code>{"{artist}"}</code>,{" "}
                <code>{"{album}"}</code>, <code>{"{title}"}</code> in{" "}
                <code>naming_format</code>.
              </li>
              <li>
                Spotify: Provide API keys to enable identification of
                playlists/albums.
              </li>
            </ul>
          </div>

          {/* Editor */}
          <div className="space-y-2">
            <div className="flex justify-between items-center">
              <label className="text-sm font-medium text-text-muted">
                Config JSON
              </label>
              <button
                onClick={handleReset}
                className="text-xs text-accent hover:underline flex items-center gap-1"
              >
                <IconRefresh size={12} /> Reset Defaults
              </button>
            </div>
            <textarea
              value={jsonString}
              onChange={(e) => {
                setJsonString(e.target.value);
                setError(null);
              }}
              className="w-full h-64 bg-surface-base border border-border rounded-lg p-3 font-mono text-sm focus:outline-none focus:ring-1 focus:ring-accent resize-none text-text-primary"
              spellCheck={false}
            />
            {error && <p className="text-error text-sm">{error}</p>}
          </div>

          {/* Danger Zone */}
          <div className="border border-error/20 bg-error/5 rounded-lg p-4 space-y-3">
            <h4 className="text-sm font-semibold text-error flex items-center gap-2">
              <IconAlertTriangle size={16} /> Danger Zone
            </h4>
            <p className="text-xs text-text-muted">
              Deleting plugin data will remove all generated files, embeddings,
              and cache associated with this plugin.
            </p>
            <Button
              variant="secondary"
              onClick={handleDeleteData}
              disabled={isDeleting}
              className="w-full border-error/50 text-error hover:bg-error/10 hover:border-error"
            >
              <IconTrash size={16} className="mr-2" />
              {isDeleting ? "Deleting..." : "Delete Plugin Data"}
            </Button>
          </div>
        </div>

        <div className="p-4 border-t border-border bg-surface-base flex justify-end gap-3 shrink-0">
          <Button variant="ghost" onClick={onClose} disabled={isSaving}>
            Cancel
          </Button>
          <Button onClick={handleSave} disabled={isSaving}>
            <span className="flex items-center gap-2">
              <IconDeviceFloppy size={18} />
              {isSaving ? "Saving..." : "Save Changes"}
            </span>
          </Button>
        </div>
      </div>
    </div>
  );
}
