-- AI Infrastructure Migration
-- Description: Enable pgvector and create embeddings table for audio similarity
-- Order: 004

-- 1. Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Create track_embeddings table
-- This table stores the high-dimensional vectors generated by the 'Brain' plugin.
-- Models like clap-htsat-unfused produce 512-dimension vectors.
CREATE TABLE IF NOT EXISTS track_embeddings (
    track_id UUID PRIMARY KEY REFERENCES tracks(id) ON DELETE CASCADE,
    embedding vector(512), -- Match with AI_EMBEDDING_DIM in config
    model_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create HNSW index for fast similarity search
-- HNSW is usually faster than IVFFlat for high-dimensional data in pgvector
CREATE INDEX IF NOT EXISTS idx_track_embeddings_vector ON track_embeddings 
USING hnsw (embedding vector_cosine_ops);

-- 4. Update trigger for track_embeddings
CREATE OR REPLACE FUNCTION update_track_embeddings_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER trigger_update_track_embeddings_timestamp
    BEFORE UPDATE ON track_embeddings
    FOR EACH ROW
    EXECUTE FUNCTION update_track_embeddings_timestamp();

COMMENT ON TABLE track_embeddings IS 'Stores audio embeddings for similarity-based features (Brain Plugin)';
